name: pySM
dependencies:
  - python=2.7
  - pip
  - nomkl
  - numpy=1.10.1
  - scipy=0.17.0
  - numba=0.24.0
  - pandas=0.18.0
  - pip:
    - pyimzML==1.1.1
    - pyMSpec==0.1
    - pyImagingMSpec==0.1.1
